// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "5de69633-a156-42c7-b15d-0e76aad3f1d2");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1638656146);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1638656163);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1638656180);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2126);
user_pref("browser.cache.disk.capacity", 337920);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1638656116);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d528dd3b-c106-4f49-9155-2154d6689fd9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1638656130385");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1638657948385");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1638656122679");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1638677722679");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210927121355");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1638656180");
user_pref("browser.slowStartup.averageTime", 1522);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20210927121355");
user_pref("browser.startup.homepage_override.mstone", "78.15.0");
user_pref("browser.startup.lastColdStartupCheck", 1638656180);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1638656170089");
user_pref("distribution.iniFile.exists.appversion", "78.15.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "d329502943914734a808b0fdb9498d05");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210927121355");
user_pref("extensions.lastAppVersion", "78.15.0");
user_pref("extensions.lastPlatformVersion", "78.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"7b6d7221-0784-4a01-8ec0-8c9c9063cd70\",\"formautofill@mozilla.org\":\"4bc84d5f-eaf1-4138-96a0-acdde6f941bb\",\"screenshots@mozilla.org\":\"08bccc21-a4c0-4e31-a44c-a45bcd2a84b3\",\"webcompat-reporter@mozilla.org\":\"a0d44956-fc02-4ea9-9f86-4c330ccc6e95\",\"webcompat@mozilla.org\":\"b60435ac-56ef-43f2-b6ae-1fd3767cf383\",\"default-theme@mozilla.org\":\"3f709318-6621-4705-b9e0-1be6eed3b33a\",\"google@search.mozilla.org\":\"e773fd5d-01b5-482a-8a15-3ab347a554f1\",\"amazondotcom@search.mozilla.org\":\"ad76e2cc-8546-4032-aa8e-ceff703fd46c\",\"wikipedia@search.mozilla.org\":\"f70456cf-552f-41f2-b5f0-585a01d7fbc3\",\"bing@search.mozilla.org\":\"ea14b5e3-2eb6-451c-ab62-0e9a933ba417\",\"ddg@search.mozilla.org\":\"d8d82a8b-ecdf-4bff-8490-c93f897d9ee5\",\"firefox-compact-dark@mozilla.org\":\"a8e52081-7d39-4a62-ab94-f69c8aca42ad\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 88412);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2459b1a6-3560-4fd8-b3d0-f1aec3236499");
user_pref("security.sandbox.plugin.tempDirSuffix", "5194f3c8-5609-4ae3-8229-9df1ab575f46");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1638656179);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210927121355");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
